import streamlit as st

generos = {
    'Sertanejo': {
        'Jorge & Mateus' : 'https://www.youtube.com/watch?v=1BszEl3ujXs',
        'Henrique & Juliano' : 'https://www.youtube.com/watch?v=9Et53l5l-FE&list=RD9Et53l5l-FE&start_radio=1',
        'Zé Neto & Cristiano' :'https://www.youtube.com/watch?v=wxLE0V9EFqg&list=RDwxLE0V9EFqg&start_radio=1',
        'Maiara & Maraisa' : 'https://www.youtube.com/watch?v=Q9q0tDPi6D4&list=RDQ9q0tDPi6D4&start_radio=1'
    },
'Rock' : {
    'Charlie Brown Jr' : 'https://www.youtube.com/watch?v=pdU0gOINdPE&list=RDpdU0gOINdPE&start_radio=1',
    "CPM 22" :'https://www.youtube.com/watch?v=RsEeyZNiwUk&list=RDRsEeyZNiwUk&start_radio=1',
    'Guns N Roses' : 'https://www.youtube.com/watch?v=lRmJZIQfjbo&list=RDlRmJZIQfjbo&start_radio=1',
    'Falling in Reverse' : 'https://www.youtube.com/watch?v=Ga2r8bpzo5k&list=RDGa2r8bpzo5k&start_radio=1'
},
'Hip Hop' : {
    'Hungria' : 'https://www.youtube.com/watch?v=HnvGaGireJM&list=RDHnvGaGireJM&start_radio=1',
    'Pacificadores' : 'https://www.youtube.com/watch?v=-5DrLPHvswY&list=RD-5DrLPHvswY&start_radio=1',
    'Misael' : 'https://www.youtube.com/watch?v=3T1UWJe78mg&list=RD3T1UWJe78mg&start_radio=1',
    'Tribo da Periferia' : 'https://www.youtube.com/watch?v=euAM7IQuBck&list=RDeuAM7IQuBck&start_radio=1'
},
'Funk' : {
    'Mc Lan' : 'https://www.youtube.com/watch?v=8hblgBhcppI&list=RD8hblgBhcppI&start_radio=1',
    'Mc Hariel' : 'https://www.youtube.com/watch?v=tUJXtHMXDY0&list=RDtUJXtHMXDY0&start_radio=1',
    'Mc Don Juan' : 'https://www.youtube.com/watch?v=rTCyZdJGspE&list=RDrTCyZdJGspE&start_radio=1',
    'Mc Guime' : 'https://www.youtube.com/watch?v=gyXkaO0DxB8&list=RDgyXkaO0DxB8&start_radio=1'
}
}

st.sidebar.title('Ritmia do Som')
st.sidebar.image('logo app.png')

genero = st.sidebar.selectbox('Escolha um genero musical',generos.keys())

artista = st.sidebar.selectbox('Escolha um artista',generos[genero])

st.title(artista)
st.markdown('|---|')
video, sobre = st.tabs(['Vídeo','Sobre o artista'])

with video: 
    st.video(generos[genero][artista])

with sobre:
    if artista == 'Jorge & Mateus':
        st.markdown("""Jorge & Mateus é uma dupla brasileira de música sertaneja, formada em Itumbiara em 2005 pelos cantores Jorge Barcelos (vocal) e Mateus Liduário (vocal e guitarra).[1]
            Precursores do sertanejo universitário, Jorge & Mateus lançaram seu álbum de estreia em 2007, Ao Vivo em Goiânia, produzido por Pinocchio, que alcançou popularidade no país através das canções "Pode Chorar", "De Tanto Te Querer" e "Tem Nada a Ver", o que fez a dupla investir em outros trabalhos ao vivo, que fortaleceram sua notoriedade. Em 2010, foi lançado Aí já Era, primeiro álbum de estúdio da dupla, que marcou o início da parceria com o produtor Dudu Borges, que durou até Os Anjos Cantam em 2015.[2] O som da dupla, durante este período, ganhou influências de gêneros como o pop e folk rock, e os músicos chegaram a gravar um álbum em Londres. Ao longo da segunda metade da década de 2010, foi lançado Como. Sempre Feito. Nunca (2016) e Terra Sem CEP (2018) e, entre eles, um álbum comemorativo de 10 anos que reuniu mais de 80 mil pessoas em Brasília em 2016. Nos últimos anos, a banda produziu Tudo em Paz (2021), É Simples Assim (2022) e Check-In (2024) e anunciou uma pausa de suas atividades. """)
    elif artista == 'Henrique & Juliano': 
        st.markdown("""Henrique & Juliano é uma dupla sertaneja formada pelos irmãos Ricelly Henrique Tavares Reis (23 de maio de 1989) e Edson Alves dos Reis Junior (27 de novembro de 1990), ambos nascidos na cidade de Palmeirópolis no interior do estado do Tocantins. São os atuais artistas mais populares do Brasil de 2025 de acordo com a lista da Billboard Artistas 25.
             Ricelly Henrique Tavares Reis, o "Henrique", e Edson Alves dos Reis Junior , o "Juliano", são irmãos, nascidos na cidade de Palmeirópolis, no estado brasileiro do Tocantins, filhos de Maria Tavares Reis e Edson Alves dos Reis, o grande incentivador no gosto dos dois filhos pela música sertaneja, foram Influenciados pelo sucesso da dupla João Paulo & Daniel, começaram a se apresentar nas rádios do município e para um grande público interpretando e dublando quando crianças, os sucessos da banda Mamonas Assassinas, sucesso em todo o Brasil na década de 90, e a vida os obrigou a tomar um rumo diferente do que eles sempre sonharam, que foi viver da música""")            
    elif artista == 'Zé Neto & Cristiano' :
        st.markdown("""Zé Neto & Cristiano é uma dupla sertaneja brasileira formada em 2011 na cidade de São José do Rio Preto pelos músicos Zé Neto (vocal) e Cristiano Vaccari (vocal).
            Os músicos ganharam popularidade inicial em 2016, com o lançamento de Ao Vivo em São José do Rio Preto, que conteve a música "Seu Polícia". Em 2018, a dupla se tornou um dos maiores nomes sertanejos do Brasil por meio dos projetos Acústico e Esquece o Mundo Lá Fora, que reuniram músicas como "Status que Eu não Queria", "Bebida na Ferida", "Notificação Preferida" e "Largado às Traças", que foi um dos principais sucessos brasileiros do ano. Nos anos seguintes, Zé Neto & Cristiano seguiu com lançamentos anuais, com os títulos Por Mais Beijos ao Vivo (2020) e Chaaama (2021), Tarja Preta (2022) e Escolhas (2023). O trabalho mais recente da dupla é Intenso (2024).""")
    elif artista == 'Maiara & Maraisa' :    
        st.markdown("""Maiara & Maraisa é uma dupla sertaneja de cantoras, compositoras, multi-instrumentistas e empresárias brasileiras, formada pelas irmãs gêmeas Maiara e Maraisa. Se tornaram conhecidas nacionalmente por hits como "10%" e "Medo Bobo".
            Filhas de Marco César Rosa Pereira e Almira Henrique, Maiara e Maraisa nasceram em São José dos Quatro Marcos, no Mato Grosso, em 31 de dezembro de 1987, e passaram a infância e adolescência em diversas cidades do país. Inicialmente, antes da fama, moraram em sua cidade natal, e logo após nascerem mudaram-se para Juruena, ao longo da infância e adolescência também viveram na cidade de Rondonópolis onde o pai Marcos César trabalhou como bancário, e nas cidades de Araguaína, Montes Claros, Governador Valadares e Belo Horizonte.""")
    elif artista == 'Charlie Brown Jr' :
        st.markdown("""Charlie Brown Jr. foi uma banda de rock brasileira formada em Santos, em 1992, tendo em sua formação original o vocalista Chorão, o baixista Champignon, os guitarristas Marcão Britto e Thiago Castanho, além do baterista Renato Pelado.[5] Sua discografia contabiliza dez álbuns de estúdio lançados, três álbuns ao vivo e sete DVDs. [6] Excetuando Chorão, todos os membros da banda são naturais de Santos, uma vez que o vocalista é natural de São Paulo.[7]
            A banda encerrou suas atividades em 2013, quando na madrugada do dia 6 de março daquele ano, Chorão foi encontrado morto em seu apartamento em São Paulo, devido a uma overdose de cocaína. Posteriormente a isso os demais membros do Charlie Brown Jr. se reuniram em projetos distintos para preservar a memória de Chorão e manter o seu legado vivo. Em 2013, logo após à morte de Chorão, os membros remanescentes chegaram a mudar o nome da banda para A Banca, com Champignon assumindo os vocais.[8][9] Porém o grupo encerrou as atividades em setembro do mesmo ano, após Champignon cometer suicídio em sua casa, também em São Paulo, na madrugada do dia 9 daquele mês.""")    
    elif artista == 'CPM 22' :
        st.markdown("""CPM 22 é uma banda de rock brasileira formada em 1995 na cidade de Barueri, São Paulo. A banda é formada atualmente por Badauí (vocal), Luciano Garcia (guitarra), Phil Fargnoli (guitarra), Ali Zaher Jr. (baixo) e Daniel Siqueira (bateria). A banda já abriu shows de bandas internacionais como Lagwagon, No Fun at All, Down by Law e System of a Down. O CPM 22 foi uma das poucas bandas do hardcore brasileiro a ganhar um disco de ouro e fazer sucesso no mainstream, e com isso, abriu as portas para uma nova geração de bandas de rock brasileiras. Em 2008, ganharam um Grammy Latino de melhor álbum de rock brasileiro.[1]""")
    elif artista == 'Guns N Roses':  
        st.markdown("""Guns N' Roses é uma banda americana de hard rock, formada em Hollywood, em 1985. A banda já lançou seis álbuns de estúdio, três EPs e um álbum ao vivo. O co-fundador e líder Axl Rose e o tecladista Dizzy Reed são os únicos membros da formação clássica no atual Guns N 'Roses.
             O estilo musical, a presença em palco e a imagem de bad boy da banda contribuíram para o sucesso do grupo durante uma nova era de dominação do hard rock no final dos anos 1980 e início dos anos 1990. Os fãs da banda dizem que esta perdeu a sua essência, desde a saída do ex-guitarrista Slash.""")
    elif artista == 'Falling in Reverse':
        st.markdown("""Falling in Reverse é uma banda de post-hardcore americana formada em 2008 por Ronnie Radke em Las Vegas, Nevada. A banda é liderada pelo vocalista Ronnie Radke, junto com os guitarristas Cristian Thompson e Derek Jones, o baterista Ryan Seaman, e o baixista Zakk Sandler.
                    Lançaram seu álbum de estreia, The Drug in Me Is You, em 26 de julho de 2011, que chegou ao número #19 na Billboard 200, vendendo 18 mil cópias em sua primeira semana de vendas. "Raised by Wolves", "The Drug in Me Is You", "I'm Not A Vampire", e "Good Girls, Bad Guys" foram lançados como singles para promover o álbum. Seu segundo álbum, Fashionably Late álbum que foi muito criticado pelos seus fãs por ter adotado um estilo diferente do seu álbum antecessor o álbum contem algumas musicas partes em rap fazendo soar como um novo estilo o rap-core. Foi lançado oficialmente em 18 de Junho de 2013, que chegou ao número #17 na Billboard 200, vendendo 20 mil cópias em sua primeira semana de vendas. "Alone", "Fashionably Late" e "Born to Lead" foram lançados como singles para promover o álbum
""")
    elif artista == 'Hungria':
        st.markdown("""Hungria ficou conhecido nacionalmente pelo seu primeiro single, "Bens Materiais", mas só alcançou sucesso fora do território nacional com as músicas "Dubai", "Lembranças", "Coração de Aço", "Beijo Com Trap", "Temporal”, "Chovendo Inimigo", "O Playboy Rodou", "Não Troco", "Quebra-Cabeça", "Um Pedido", "Insônia" e "Amor e Fé", com cada uma delas ultrapassando a marca de 100 milhões de acessos na Internet. Atualmente, um dos seus maiores hits "Lembranças", possui mais de 300 milhões de acessos no YouTube e tornou-se trilha sonora de Malhação: Viva a Diferença. Hungria lançou três álbuns de estúdio, três EPs, possui um certificado de disco de ouro em Meu Carona,[4] um certificado de single de platina em "Insônia 2",[5] um certificado de ouro em “Amor e Fé”, um certificado de platina 2x em “Outro Patamar” e “Temporal”, um certificado de diamante em “Cruzeiro da Revoada”, um certificado de ouro em “Cama de Casal”, “Quem é o Boss?”, e “Atmosfera”, um certificado de platina em “Coração de Carro Forte”,[5] e um certificado de single de platina triplo em "Eu Vou Te Buscar (Cha La La La La)", com Gusttavo Lima.[6]""")
    elif artista == 'Pacificadores':
        st.markdown("""O Grupo Pacificadores carimbou sua marca por onde passou. A formação do Grupo é bastante eclética, com músicos seguidores/ouvintes de gêneros musicais diferentes, porém, todos com o estilo Raper/R&B dentro de si, atrelado ao dia a dia. O repertório do Grupo inclui sucessos consagrados dentro do país, tais como: Não Faz Assim, Ai Bicudo, Eu Queria Mudar, além é claro de músicas R&B.
Para esquentar um pouco mais o show/baile. O estilo Rap, com várias musicas novas no mercado é uma das especialidades dos Pacificadores. Uma banda de músicos com anos de experiência e dedicação, que tem um show absolutamente perfeito, com ensaios de backings vocals inclusive, colocando a música Raper num patamar elevado, que é onde ela deve estar.""")
    elif artista == 'Misael':   
        st.markdown("""A carreira de Misael começou por acaso, aos 8 anos de idade, quando ele participou de uma gravação do grupo Pacificadores, por influência do irmão mais velho, Fábio (Neguim), produtor musical do grupo. Três anos depois, aos 11 anos, o jovem rapper entrou para a antiga formação do grupo e protagonizou a canção “Eu Queria Mudar”, que marcou o início de sua carreira, com uma grande repercussão que chegou às principais rádios de rap no Brasil e no exterior.
Desde então, Misael vem conquistando cada vez mais espaço nas rádios, televisão e outras mídias nacionais. 2019 foi um ano importante na carreira do artista. Em fevereiro ele foi uma das atrações do camarote da revista Quem, onde se apresentou no dia do Desfile das Campeãs, no Carnaval do Rio de Janeiro. Em Abril, o artista apresentou a canção “Mente Louca” no palco do Programa Raul Gil, atingindo um novo público em uma das mais importantes emissoras do país. O resultado pode ser visto em sua agenda de shows lotada, com cerca de 16 apresentações por mês, em muitas cidades do território nacional.""")
    elif artista == 'Tribo da Periferia':
        st.markdown("""Tribo da Periferia é um grupo de rap e hip hop brasiliense que nasceu nas raízes do Distrito Federal em 1998, após o garoto Luiz Fernando Correia da Silva escrever a primeira letra musical de repercussão. Seguindo a tendência dos anos 1990, onde os rappers brasileiros tinham todos nomes em inglês (Mano Brown, Ice Blue, Kl Jay) e tendo como inspiração o grupo Duckjam e Nação Hip Hop, Luiz Fernando assumiu o nome artístico de Duckjay.
A formação original do Tribo da Periferia contava com Duckjay e os ex-integrantes Mano Marley e Alisson, que ficaram até o ano 2000. Dj Bola Tribo também teve uma trajetória pelo grupo permanecendo entre 2003 e 2015.
A partir de 2016 o Tribo da Periferia passou a ser formado por Duckjay (que além de cantor é compositor e produtor musical) e Look, nome que Nelcivando Lustosa Rodrigues escolheu para seguir com ele a estrada da música. Os amigos se conheceram em 1998 e a grande sintonia entre os dois foi essencial para que a parceria desse certo.
Em uma época em que o rap sofria discriminação expressiva, até da própria periferia, o Tribo da Periferia tinha que conquistar os fãs no corpo a corpo. Não existia internet, por isso, os músicos dependiam muito das rádios e Djs para tocar as músicas nas festas. Havia dificuldades para se ter acesso a um estúdio, eles não eram vinculados a uma grande gravadora e a situação financeira dos integrantes também era um problema.""")
    elif artista == 'Mc Lan':
        st.markdown("""Caio nasceu em Diamantina, mas mudou-se para a cidade de São Paulo junto com a sua família durante a sua infância.[1] Influenciado por estilos como rock, blues e rap, Caio ingressou como locutor de uma rádio durante sua adolescência e poucos anos depois, teve a oportunidade de abrir um show do grupo de rap 509-E, composto por Afro-X e Dexter, no entanto, a performance não foi bem-sucedida.[1] Afastado da música por um tempo, Caio foi preso em 2015 e ficou em cárcere por cerca de um ano e meio, e após sair da prisão, foi morar na rua.[1]
No início de 2016, Caio decidiu dar prosseguimento a carreira de cantor e após um contato com a dona de uma lan house do bairro Jardim Silvina, localizado em São Bernardo do Campo, conseguiu um contrato para gravar a sua primeira música e deu início com o nome artístico Lan.[1] Sua primeira música de sucesso lançada foi "Cala Boca e me Mama", em meados de 2016. Em poucos meses, Lan se tornou um dos principais expoentes do chamado funk ousadia, o qual faz referências humorísticas à termos com conotação sexual.[1] Devido ao aumento da popularidade, o artista começou a realizar shows fora da região da grande São Paulo.[2]""")
    elif artista == 'Mc Hariel':    
        st.markdown("""Hariel nasceu na Vila Aurora, região da zona norte de São Paulo no ano de 1997.[2] Recebendo influência de seu pai, Celso Ribeiro, que era músico e participou do grupo Raíces de América, Hariel começou a carreira de cantor ao gravar músicas aos onze anos de idade, sendo que durante a sua adolescência trabalhou como entregador de pizzas e vendedor de cartões.[3] A primeira canção de sucesso do artista foi "Passei Sorrindo", lançada em 2014 e que recebeu um webclipe do produtor KondZilla no ano seguinte.[4] Nesta época, o autor cantava músicas do subgênero funk ousadia, com letras de duplo sentido e conotações sexuais.[3] Nos anos seguintes, também compôs músicas de sucesso do gênero de funk ostentação, como "Novo Corolla", que recebeu menção do programa Auto Esporte, da TV Globo.[5]
No entanto, a primeira vez que Hariel alcançou projeção nacional foi com a canção "Lei do Retorno", em parceria com o MC Don Juan e com gravação da GR6 Produções, acumulando mais de 270 milhões de visualizações no YouTube.[6][7] Neste ano, participou do CD Melhor Viagem do cantor Gaab, na faixa "Tem Café", em uma música com tom mais romântico e mesclando com o rap e o pagode.[8]""")
    elif artista == 'Mc Don Juan': 
        st.markdown("""Nascido em São Paulo, Matheus começou a cantar músicas aos 11 anos de idade, mas somente em 2015, aos quatorze anos, alcançou projeção nacional e adotou o nome artístico de MC Don Juan[1][2]. Sua primeira canção de sucesso foi "Me Amarro na Noite", lançada em 2016 e disponibilizada no formato de videoclipe pelo produtor KondZilla.[carece de fontes]
MC Don Juan tornou-se um dos principais representantes do funk paulista no ano de 2017, com o lançamento da canção "Oh Novinha", tanto na versão proibida, quanto na versão clean. A canção tornou-se a 20ª mais escutada do país no Spotify, além de ter entrado nas paradas musicais paraguaias.[3] A música tornou-se comentada na internet por ter sido executada e dançada ao vivo pela atriz Cláudia Raia, da Rede Globo, no programa Mais Você.[4] A música se tornou trilha sonora da novela A Força do Querer, também da Rede Globo, em cenas da personagem Bibi, protagonizada por Juliana Paes.[5] A versão clean recebeu um videoclipe também produzido por KondZilla, acumulando mais de 75 milhões de visualizações.[6]""")
    elif artista == 'Mc Guime':
        st.markdown("""Nascido em Osasco, filho de um ajudante de eletricista, Paulo Eduardo Dantas e de Maria Cristina Amaral Dantas, para ajudar o pai com as despesas da casa, Guilherme chegou a trabalhar dos 13 aos 16 em uma quitanda, idade com que começou a fazer suas primeiras músicas.[2] Considerado o maior nome do funk ostentação,[9] atualmente Guimê realiza cerca de três ou quatro shows por noite, faturando de 25 a 30 mil reais em cada noite e 500 mil por mês.[2][3][4][10]
O luxo descrito nas letras não corresponde à história de vida de Guimê, em parte, anseio do garoto humilde. Por outro lado, o funkeiro descreve novas cenas de sua vida que lembram os luxuosos clipes de rap americano dos quais é fã. Foi criado a partir dos seis meses só pelo pai, eletricista de origem humilde, a quem chamava de mãe. Cresceu em Osasco enquanto se tornava obstinado com o sucesso.[10]""")
              